In [20]:
import numpy as np
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])
arr_append = np.column_stack((arr, [1]*arr.shape[0]))
print('A:', arr_append)

arr1 = arr*0.1
arr_append1 = np.column_stack((arr1, [1]*arr1.shape[0]))
print('B:', arr_append1)


# broadcasting
# A: x(u, v)
# [[u1, v1, 1],
#  [u2, v2, 1],
#  [u3, v3, 1]]

# B: x(u', v')
# [[u1', v1', 1],
#  [u2', v2', 1],
#  [u3', v3', 1]]

# x'^T.F.x = 0

# np.expand_dims(A, 1)
# [[[u1, v1, 1],
#   [u2, v2, 1],
#   [u3, v3, 1]]]

# np.expand_dims(B, 2)
# [[[u1'],
#   [v1'],
#   [1]],

#  [[u2'],
#   [v2'],
#   [1]],

#  [[u3'],
#   [v3'],
#   [1]]]


# pa*pb=
# [[[u1'u1, u1'v1, u1'],
#   [v1'u1, v1'v1, v1'],
#   [u1, v1, 1]],

#  [[u2'u2, u2'v2, u2'],
#   [v2'u2, v2'v2, v2'],
#   [u2, v2, 1]],

#  [[u3'u3, u3'v3, u3'],
#   [v3'u3, v3'v3, v3'],
#   [u3, v3, 1]]]

# (pa*pb).reshape(arr.shape[0], -1)
# [[u1'u1, u1'v1, u1', v1'u1, v1'v1, v1', u1, v1, 1],
#  [u2'u2, u2'v2, u2', v2,'u2, v2'v2, v2', u2, v2, 1],
#  [u3'u3, u3'v3, u3', v3'u3, v3'v3, v3', u3, v3, 1]]

A: [[1 2 1]
 [3 4 1]
 [5 6 1]]
B: [[0.1 0.2 1. ]
 [0.3 0.4 1. ]
 [0.5 0.6 1. ]]


In [21]:
pa = np.expand_dims(arr_append, 2)
print(pa.shape)
pa

(3, 3, 1)


array([[[1],
        [2],
        [1]],

       [[3],
        [4],
        [1]],

       [[5],
        [6],
        [1]]])

In [22]:
pb = np.expand_dims(arr_append1, 1)
print(pb.shape)
pb

(3, 1, 3)


array([[[0.1, 0.2, 1. ]],

       [[0.3, 0.4, 1. ]],

       [[0.5, 0.6, 1. ]]])

In [23]:
pc = pa*pb
pc

array([[[0.1, 0.2, 1. ],
        [0.2, 0.4, 2. ],
        [0.1, 0.2, 1. ]],

       [[0.9, 1.2, 3. ],
        [1.2, 1.6, 4. ],
        [0.3, 0.4, 1. ]],

       [[2.5, 3. , 5. ],
        [3. , 3.6, 6. ],
        [0.5, 0.6, 1. ]]])

In [24]:
pc = pc.reshape(arr_append.shape[0], -1)
pc

array([[0.1, 0.2, 1. , 0.2, 0.4, 2. , 0.1, 0.2, 1. ],
       [0.9, 1.2, 3. , 1.2, 1.6, 4. , 0.3, 0.4, 1. ],
       [2.5, 3. , 5. , 3. , 3.6, 6. , 0.5, 0.6, 1. ]])

In [11]:
arr1 = np.concatenate((arr_append, np.zeros_like(arr_append)), axis=1).reshape((-1, 4))
arr1

array([[1, 2, 3, 1],
       [0, 0, 0, 0],
       [4, 5, 6, 1],
       [0, 0, 0, 0],
       [7, 8, 9, 1],
       [0, 0, 0, 0]])

In [12]:
arr2 = np.concatenate((np.zeros_like(arr_append), arr_append), axis=1).reshape((-1, 4))
arr2

array([[0, 0, 0, 0],
       [1, 2, 3, 1],
       [0, 0, 0, 0],
       [4, 5, 6, 1],
       [0, 0, 0, 0],
       [7, 8, 9, 1]])

In [13]:
uv = np.array([[0.1, 0.2],
                [0.3, 0.4],
                [0.5, 0.6]])

In [14]:
arr3 = -np.multiply(uv.reshape((-1, 1)).repeat(3, axis=1), arr.repeat(2, axis=0))
arr3

array([[-0.1, -0.2, -0.3],
       [-0.2, -0.4, -0.6],
       [-1.2, -1.5, -1.8],
       [-1.6, -2. , -2.4],
       [-3.5, -4. , -4.5],
       [-4.2, -4.8, -5.4]])

In [16]:
arr4 = np.concatenate((arr1, arr2, arr3), axis=1)
arr4

array([[ 1. ,  2. ,  3. ,  1. ,  0. ,  0. ,  0. ,  0. , -0.1, -0.2, -0.3],
       [ 0. ,  0. ,  0. ,  0. ,  1. ,  2. ,  3. ,  1. , -0.2, -0.4, -0.6],
       [ 4. ,  5. ,  6. ,  1. ,  0. ,  0. ,  0. ,  0. , -1.2, -1.5, -1.8],
       [ 0. ,  0. ,  0. ,  0. ,  4. ,  5. ,  6. ,  1. , -1.6, -2. , -2.4],
       [ 7. ,  8. ,  9. ,  1. ,  0. ,  0. ,  0. ,  0. , -3.5, -4. , -4.5],
       [ 0. ,  0. ,  0. ,  0. ,  7. ,  8. ,  9. ,  1. , -4.2, -4.8, -5.4]])

In [18]:
a = np.array([[0., 1.,  0.,  1.,  2.,  0.],
            [0., 2.,  0.,  0.,  1.,  0.],
            [1., 0.,  1.,  0.,  0.,  4.],
            [0., 0.,  0.,  2.,  3.,  0.]]).T

b = np.array([1, 0, 0, 0, 0, 0])
x, residuals, rank, s = np.linalg.lstsq(a, b, rcond=-1)
print(f'x: {x}, residuals: {residuals}, s: {x}')
x, residuals, rank, s = np.linalg.lstsq(a, b, rcond=None)
print(f'x: {x}, residuals: {residuals}, s: {x}')

x: [-1.38045395e+15  6.90226974e+14  0.00000000e+00  6.90226974e+14], residuals: [0.0015373], s: [-1.38045395e+15  6.90226974e+14  0.00000000e+00  6.90226974e+14]
x: [3.68746598e-17 4.17086763e-17 5.55555556e-02 3.68698373e-17], residuals: [], s: [3.68746598e-17 4.17086763e-17 5.55555556e-02 3.68698373e-17]


In [9]:
import numpy as np

a = np.arange(20*9).reshape(20, 9)

In [10]:
b = a[:, 0].copy()
# we impose a condition that first term be 1, 
x = np.linalg.lstsq(a[:, 1:], -b)[0]
x = np.r_[1, x]
x /= np.linalg.norm(x)
print(np.linalg.matrix_rank(x))
print(np.matmul(a, x))

1
[-5.10702591e-15 -2.22044605e-15 -8.88178420e-16  8.88178420e-16
  5.32907052e-15 -3.55271368e-15  5.32907052e-15  1.24344979e-14
  1.42108547e-14  1.42108547e-14  7.10542736e-15  2.48689958e-14
  1.06581410e-14  3.55271368e-15  1.77635684e-14  2.13162821e-14
  1.42108547e-14  3.55271368e-14  1.42108547e-14  2.84217094e-14]


In [22]:
U, s, V = np.linalg.svd(a, full_matrices=False)
x = V[-1]
# print(x)
print(np.linalg.matrix_rank(x))
print(np.matmul(a, x))

1
[-1.33226763e-15 -4.44089210e-15 -6.21724894e-15 -1.50990331e-14
 -2.04281037e-14 -2.30926389e-14 -2.48689958e-14 -3.01980663e-14
 -3.19744231e-14 -3.73034936e-14 -4.26325641e-14 -4.61852778e-14
 -4.61852778e-14 -4.97379915e-14 -5.68434189e-14 -6.39488462e-14
 -8.17124146e-14 -6.75015599e-14 -6.39488462e-14 -9.23705556e-14]


In [23]:
U, s, V = np.linalg.svd(x.reshape((3, 3)))
s[-1] = 0
x = np.matmul(U, np.diagflat(s), V)
print(np.matmul(a, x.reshape((-1))))

[-1.33226763e-15 -4.44089210e-15 -6.21724894e-15 -1.50990331e-14
 -2.04281037e-14 -2.30926389e-14 -2.48689958e-14 -3.01980663e-14
 -3.19744231e-14 -3.73034936e-14 -4.26325641e-14 -4.61852778e-14
 -4.61852778e-14 -4.97379915e-14 -5.68434189e-14 -6.39488462e-14
 -8.17124146e-14 -6.75015599e-14 -6.39488462e-14 -9.23705556e-14]


In [5]:
import numpy as np

a = np.array([[1, 0],
             [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [6]:

a.dot(b)

array([[4, 1],
       [2, 2]])

In [7]:
a @ b

array([[4, 1],
       [2, 2]])

In [4]:
import numpy as np
ratio = 0.1
arr = np.tile(np.arange(1, 50).reshape(-1, 1), 2)

num_noise = int(arr.shape[0] * ratio)
temp = np.concatenate((np.ones(num_noise), np.zeros(arr.shape[0]-num_noise)), axis=0)
np.random.shuffle(temp)
print(temp)

temp1 = arr.copy()[temp==1]
np.random.shuffle(temp1)
print(temp1)

# for i in range(num_noise):
#     # print(arr[np.argwhere(temp==1)[i]],": ", temp1[i])
#     arr[np.argwhere(temp==1)[i]] = temp1[i]
arr[temp==1] = temp1
arr

[0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1.]
[[39 39]
 [49 49]
 [ 5  5]
 [10 10]]


array([[ 1,  1],
       [ 2,  2],
       [ 3,  3],
       [ 4,  4],
       [39, 39],
       [ 6,  6],
       [ 7,  7],
       [ 8,  8],
       [ 9,  9],
       [49, 49],
       [11, 11],
       [12, 12],
       [13, 13],
       [14, 14],
       [15, 15],
       [16, 16],
       [17, 17],
       [18, 18],
       [19, 19],
       [20, 20],
       [21, 21],
       [22, 22],
       [23, 23],
       [24, 24],
       [25, 25],
       [26, 26],
       [27, 27],
       [28, 28],
       [29, 29],
       [30, 30],
       [31, 31],
       [32, 32],
       [33, 33],
       [34, 34],
       [35, 35],
       [36, 36],
       [37, 37],
       [38, 38],
       [ 5,  5],
       [40, 40],
       [41, 41],
       [42, 42],
       [43, 43],
       [44, 44],
       [45, 45],
       [46, 46],
       [47, 47],
       [48, 48],
       [10, 10]])

In [3]:
import numpy as np
a = np.array([[1, 5], [3, 6]])

In [4]:
np.var(a)

3.6875

In [5]:
np.var(a, axis=0)

array([1.  , 0.25])

In [6]:
np.var(a, axis=1)

array([4.  , 2.25])

In [14]:
a.mean(axis=0)

array([2. , 5.5])

In [15]:
a.mean(axis=1)

array([3. , 4.5])

In [16]:
(a-a.mean(axis=0))

array([[-1. , -0.5],
       [ 1. ,  0.5]])

In [23]:
(a-a.mean(axis=0))**2

array([[1.  , 0.25],
       [1.  , 0.25]])

In [28]:
np.mean(np.sum((a-a.mean(axis=0))**2, axis=1), axis=0)

1.25

In [1]:
a = 3
b = a
print(b)
a = 4
print(a)
print(b)

3
4
3
